### ISSUE TITLE
Error on new devcontainer configuration from codespace

### ISSUE THREAD

**Issue by Malix-Labs** [devcontainers-community/templates-jupyter-datascience-notebooks#3]
In VSCode, from the default image (`mcr.microsoft.com/devcontainers/universal:2`), creating any new `jupyter-datascience-notebooks` devcontainer configuration throws an error

## Reproduction Steps

1. Create a new codespace (by default, it will be on `mcr.microsoft.com/devcontainers/universal:2`)
2. Try to create a new devcontainer configuration with `jupyter-datascience-notebooks` (or any other)

## Logs

> Application of the template failed.

```log
[DevContainerJsonSupport V] [2024-04-17T17:27:55.079Z] Preparing to apply Template 'ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks:latest'

[DevContainerJsonSupport V] [2024-04-17T17:27:55.086Z] Running Dev Containers CLI:   templates apply --workspace-folder /tmp/tmp-output-dir-1713374875080 --template-id ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks:latest --template-args {"baseVariant":"scipy-notebook","imageVariant":"latest"} --features [] --tmp-dir /tmp/tmp-dir-1713374875080 --log-level debug

[DevContainerJsonSupport V] [2024-04-17T17:27:55.088Z] Start: Run: /vscode/bin/linux-x64/e170252f762678dec6ca2cc69aba1570769a5d39/node /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /tmp/tmp-output-dir-1713374875080 --template-id ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks:latest --template-args {"baseVariant":"scipy-notebook","imageVariant":"latest"} --features [] --tmp-dir /tmp/tmp-dir-1713374875080 --log-level debug

[Client:extension:417b:resolver:resolve:1:background-tasks:activity-monitor:vscode-activity-provider V] sending activity heartbeat
[Client:extension:417b:resolver:resolve:1:background-tasks:activity-monitor:vscode-activity-provider I] Executed notify-codespace-of-client-activity using gRPC
[Client:extension:417b:resolver:resolve:1:background-tasks:activity-monitor:vscode-activity-provider I] Activity signal sent with result true
[DevContainerJsonSupport V] [2024-04-17T17:27:55.433Z] [2024-04-17T17:27:55.432Z] @devcontainers/cli 0.56.2. Node.js v18.18.2. linux 6.2.0-1019-azure x64.

[DevContainerJsonSupport V] [2024-04-17T17:27:56.179Z] /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6107

[DevContainerJsonSupport V] [2024-04-17T17:27:56.179Z]         return paths.every((q) => q[0] === fn) && dirs.every((q) => q[0] instanceof Set && q[0].has(fn));

[DevContainerJsonSupport V] [2024-04-17T17:27:56.179Z]                                    ^

[DevContainerJsonSupport V] [2024-04-17T17:27:56.179Z] TypeError: Cannot read properties of undefined (reading '0')

[DevContainerJsonSupport V] [2024-04-17T17:27:56.180Z]     at /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6107:36

[DevContainerJsonSupport V] [2024-04-17T17:27:56.180Z]     at Array.every (<anonymous>)

[DevContainerJsonSupport V] [2024-04-17T17:27:56.180Z]     at check (/home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6107:22)

[DevContainerJsonSupport V] [2024-04-17T17:27:56.180Z]     at run (/home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6110:33)

[DevContainerJsonSupport V] [2024-04-17T17:27:56.181Z]     at /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6150:31

[DevContainerJsonSupport V] [2024-04-17T17:27:56.182Z]     at Set.forEach (<anonymous>)

[DevContainerJsonSupport V] [2024-04-17T17:27:56.182Z]     at clear (/home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6150:14)

[DevContainerJsonSupport V] [2024-04-17T17:27:56.182Z]     at /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6114:18

[DevContainerJsonSupport V] [2024-04-17T17:27:56.183Z]     at done (/home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6616:11)

[DevContainerJsonSupport V] [2024-04-17T17:27:56.183Z]     at /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js:6708:11

[DevContainerJsonSupport V] [2024-04-17T17:27:56.185Z] Node.js v18.18.2

[DevContainerJsonSupport V] [2024-04-17T17:27:56.188Z] Stop (1100 ms): Run: /vscode/bin/linux-x64/e170252f762678dec6ca2cc69aba1570769a5d39/node /home/codespace/.vscode-remote/extensions/github.codespaces-1.16.19/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /tmp/tmp-output-dir-1713374875080 --template-id ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks:latest --template-args {"baseVariant":"scipy-notebook","imageVariant":"latest"} --features [] --tmp-dir /tmp/tmp-dir-1713374875080 --log-level debug

[DevContainerJsonSupport V] [2024-04-17T17:27:56.189Z] Exit code 1

```

**Comment by Malix-Labs** [comment]
Hey, can this be escalated ?
It may be a greater issue than just Codespaces, given how its base image has common dependencies.

**Comment by david4096** [comment]
I also had this error trying to apply the template. I cannot use this dev container template currently

**Comment by linkion** [comment]
I'm also having this issue with the jupyter-datascience-notebook

```
[700101 ms] Preparing to apply Template 'ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks'
[700102 ms] Running Dev Containers CLI:   templates apply --workspace-folder /tmp/tmp-output-dir-1738180916838 --template-id ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks --template-args {"baseVariant":"datascience-notebook","imageVariant":"latest"} --features [] --tmp-dir /tmp/tmp-dir-1738180916838 --log-level debug --omit-paths []
[700102 ms] Start: Run: /usr/share/code/code /var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /tmp/tmp-output-dir-1738180916838 --template-id ghcr.io/devcontainers-community/templates/jupyter-datascience-notebooks --template-args {"baseVariant":"datascience-notebook","imageVariant":"latest"} --features [] --tmp-dir /tmp/tmp-dir-1738180916838 --log-level debug --omit-paths []
[700285 ms] [2025-01-29T20:01:57.022Z] @devcontainers/cli 0.72.0. Node.js v20.18.1. linux 6.11.8-300.fc41.x86_64 x64.
[700290 ms] [2025-01-29T20:01:57.027Z] Loading 149 extra certificates from /etc/ssl/certs/ca-certificates.crt.
[700503 ms] [2025-01-29T20:01:57.240Z] Start: Run: docker-credential-secret get
[700510 ms] [2025-01-29T20:01:57.247Z] Stop (7 ms): Run: docker-credential-secret get
[700512 ms] [2025-01-29T20:01:57.249Z] Stop (9 ms): Run: docker-credential-secret get
[700955 ms] [2025-01-29T20:01:57.692Z] Files to omit: 'devcontainer-template.json, README.md, NOTES.md'
[700962 ms] /var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9
[700962 ms] <truncated>
[700963 ms] TypeError: Cannot read properties of undefined (reading '0')
[700963 ms]     at /var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:40696
[700963 ms]     at Array.every (<anonymous>)
[700964 ms]     at n (/var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:40686)
[700964 ms]     at o (/var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:40767)
[700964 ms]     at /var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:41194
[700964 ms]     at Set.forEach (<anonymous>)
[700964 ms]     at s (/var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:41183)
[700964 ms]     at /var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:40791
[700964 ms]     at i (/var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:48834)
[700965 ms]     at /var/home/patrickorave/.vscode/extensions/ms-vscode-remote.remote-containers-0.394.0/dist/spec-node/devContainersSpecCLI.js:9:49906
[700965 ms] Node.js v20.18.1
[700967 ms] Exit code 1
```

**Comment by Malix-Labs** [comment]
Still happening
